name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Java
      uses: maven/setup-java@v1
      with:
        java-version: '11'        
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml      
    - name: Test with Maven
      run: mvn -B test --file pom.xml